name: "Defect Issue"
description: "Register and track a Defect"
title: "[Defect] [ptag] [itag] [utag] Text string"
labels: ["Analysis", "Comment", "Defect"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ```
        Example:
        [Defect] [1x] [IMU] Partial loss of data
        ```

  - type: input
    id: references
    attributes:
      label: References
      placeholder: "#1234"
    validations:
      required: false

  - type: input
    id: item_name
    attributes:
      label: Item name/version
      placeholder: "If apply, E.g: Veronte AP 4.8"
    validations:
      required: false

  - type: input
    id: Additional_files
    attributes:
      label: Config files
      placeholder: "If apply, Attached .zip .json file"
    validations:
      required: false

  - type: textarea
    id: defect_description
    attributes:
      label: Defect description
      placeholder: "Describe the defect, steps to reproduce, related URLs, screenshots, tracebacks, or errors"
    validations:
      required: true