name: "Occurence Report"
description: "Notificar un suceso: incidente, accidente u otro suceso relevante para la seguridad operacional"
title: "[Occurrence] [ptag] [itag] [Customer] Text string"
labels: ["Analysis", "Comment", "Safety", "Occurrence Report"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ```
        Ejemplo:
        [Occurrence] [1xVeronte] [Xsun] Parachute unintentional deployment
        ```

  - type: input
    id: references
    attributes:
      label: References
      placeholder: "#1234"
    validations:
      required: false

  - type: dropdown
    id: tipo_suceso
    attributes:
      label: Tipo de suceso
      description: |
        - **Accidente:** el incidente ha causado lesiones mortales o graves, por contacto directo con cualquier parte de la aeronave, incluso las partes que se hayan desprendido de ellas. El incidente ha causado daños o roturas estructurales que afectan adversamente su resistencia estructural, su performance o sus características y que normalmente exigen una reparación importante. La aeronave desaparece o es totalmente inaccesible.
        - **Incidente grave:** el incidente en el que intervienen circunstancias que hubo una alta probabilidad de que ocurriera un accidente.
        - **Incidente leve:** el suceso ha causado que el objetivo de la operación no se llevara a cabo y se tuvo que cancelar la operación.
      options:
        - Selecciona una opción...
        - Accidente
        - Incidente grave
        - Incidente leve
        - Otro
    validations:
      required: true

  - type: textarea
    id: descripcion_suceso
    attributes:
      label: Descripción
      description: Breve descripción, que haga hincapié en aquellos detalles que permitan la reconstrucción del suceso para su análisis. Si la descripción proviene de un issue, referenciarlo.
      placeholder: Describe el suceso...
    validations:
      required: true

  - type: textarea
    id: info_suceso_posterior
    attributes:
      label: 🠗 Resolución (a rellenar por quien gestione el suceso)
      description: Este apartado se rellenará más adelante. Crear issue sin rellenarlo.
      value: |
        Seguimiento  
        -  
        <!-- Detallar los resultados que se vayan obteniendo de la investigación del suceso -->  
        <!-- Si la investigación se lleva a cabo en otro issue, referenciarlo -->

        Acciones de seguridad operacional  
        -  
        <!-- Acciones a tomar a partir de las conclusiones del seguimiento del suceso -->
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        See [P.539 - Notificación y análisis de sucesos](https://documentation.embention.net/539/en/latest/index.html) for additional information
