name: "Problem Report"
description: "Register and track a Problem Report (PR)"
title: "[PR] [ptag] [itag] [utag] Text string"
labels: ["Analysis", "Comment", "PR"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ```
        Example:
        [PR] [1x] [IMU] Missing requirements and verification review
        ```

  - type: input
    id: references
    attributes:
      label: References
      placeholder: "#1234"
    validations:
      required: false

  - type: input
    id: item_name
    attributes:
      label: Item name/version
      placeholder: "If applicable, E.g: Veronte AP 4.8"
    validations:
      required: false

  - type: input
    id: Additional_files
    attributes:
      label: Config files
      placeholder: "If applicable, Attached .zip .json file"
    validations:
      required: false

  - type: textarea
    id: problem_description
    attributes:
      label: Problem description
      placeholder: "Describe the problem, steps to reproduce, related URLs, screenshots, tracebacks, or errors"
    validations:
      required: true

  - type: checkboxes
    id: classification_confirmation
    attributes:
      label: Confirm classification label added
      description: Confirm that you have  added the appropriate classification label to this issue (Significant, Functional, Process, Life-cycle Data, Other), in accordance with [P.411 - Problem Reporting](https://documentation.embention.net/411/en/017/index.md#classification-of-pr)
      options:
        - label: I have added the appropriate classification label
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        > [!WARNING]
        > ### As PR author, you must:
        > 
        > - Assign the issue to the corresponding PM (Project Manager) or IM (Item Manager)
        > - Be sure to add the label of the department that is most closely related to the PR    

  - type: textarea
    id: info_suceso_posterior
    attributes:
      label: PR monitoring
      description: This section will be filled in later. Create the issue without completing it.
      value: |
        
        **Impact assessment**
        <!-- If not applicable, explicitly indicate the reasons and check the box-->
        - [ ] Functional limitations/operational restrictions at the equipment level (If applicable):
        <!-- The impact of an open PR (Problem Report) existing at the time of product sale or certification. If it is not applicable, explicitly state there are no functional or operational restrictions -->
        
        - [ ] Relationship with other PRs/issues (If applicable): 
        <!-- Link issues to their outputs, including related repository commits with the change control activity information. State "None" if not applicable -->
        
        - [ ] Root cause (If Functional/Significant PR):
        <!-- Include root cause type (Procedure, Training, Resources, Human Error, Attitude) and a brief explanation -->  

        - [ ] Affected artifacts and processes (If applicable):
        <!-- Identify all affected artifacts and processes such as: requirements, design documents, code, test cases, verification procedures, hardware components, configuration items, etc. -->

        - [ ] Assessment results (If applicable):
        <!-- List here the description of any mitigations or justifications used to:
        <!-- - Significant PR: substantiate the acceptability of the PR safety effect.
        <!-- - Functional PR: to reduce the PR safety effect to Minor or No Effect
        <!-- - Process PR: describe the extent or nature of the process non-compliance or deficiency that cannot have a safety or functional effect but might contribute to not satisfying the applicable development assurance objectives.
        <!-- - Process, LCD or Other PR: justify that the error cannot have a safety or functional effect. -->  
          
        **Corrective actions**
        - [ ] 1. 
        <!-- Add all corrective actions and assign responsibles for activities -->

        **PR resolution**
        - Summary of decisions and conclusions:
        <!-- Provide a clear summary of the decisions made during PR management and the conclusions reached -->
        - Final analysis: 
        <!-- Confirm that the actions taken solve the problem -->
        
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        See [P.411 - Problem Reporting](https://documentation.embention.net/411/en/latest/index.html) for additional information